# Generated by Django 4.2.27 on 2026-01-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order in the setlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_index', models.IntegerField(default=0, help_text='Current lyric line index (0-based)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_states', to='lyrics.song')),
            ],
            options={
                'verbose_name': 'Live State',
                'verbose_name_plural': 'Live State',
            },
        ),
        migrations.CreateModel(
            name='LyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Line order within the song')),
                ('text', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lyrics.song')),
            ],
            options={
                'ordering': ['song', 'order'],
                'unique_together': {('song', 'order')},
            },
        ),
    ]
